#!/bin/sh

# Merge all base branches into master. Use this to distribute changes made on
# one machine to all others.

set -eu

master_branch=master

git checkout $master_branch

# this should be a octopus merge but nothing happens
##git merge $(git branch --format='%(refname:short)' | grep 'base-')

for base_branch in $(git branch --format='%(refname:short)' | grep 'base-'); do
    git checkout $base_branch
    # XXX with set -e, this may fail too early (b4 we visited all branches) if
    # we use --ff-only and ff is not possible
    git merge $@ $master_branch
done
